#!/usr/bin/env bash
#
#  Distribute scripts to active script bin
#
declare PROJECT_DIR=~/bin/s3g-backup
declare BIN_DIR=~/bin

__copy() {
  # move project files into script bin
  local separator='-----------------------'
  local file=''
  local -ra dirs=(
    's3gback.conf'
  )

  local -ra files=(
    's3gback'
    's3gback.common.sh'
    's3gback-lifecycle.json'
    's3gback-exclude-list.dat'
  )

  printf "%s\n" "${separator}"
  for file in "${files[@]}"; do
    cp "${file}" "${BIN_DIR}" \
      && printf "👍🏻  Copied: %s to %s\n" "${file}" "${BIN_DIR}"
  done
  printf "%s\n" "${separator}"
  for dir in "${dirs[@]}"; do
    cp -r "${dir}" "${BIN_DIR}" \
      && printf "👍🏻  Copied: %s to %s\n" "${dir}" "${BIN_DIR}"
  done
  printf "%s\n" "${separator}"

}


__control() {
  ssh control mkdir -p /home/ubuntu/bin/xs-swarm
  scp -r ~/bin/xs-swarm/* control:/home/ubuntu/bin/xs-swarm/
}
#
# Flags are for extensibility
#
declare FLAG=${1:-help}
case ${FLAG} in
  --copy|copy) __copy; exit 0; ;;
  --all|all) __copy; exit 0;  ;;
  --help|help)
    echo '
    Usage
      ./dist --help
      ./dist --copy
      ./dist --all
    '
    exit 0
    ;;
esac

# in case we get no flags, copy (for now)
__copy
